### ISSUE TITLE
IOError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by LeonardKnuth** [carpedm20/pixel-rnn-tensorflow#6]
Hi, @carpedm20 

When I run the command: 

> $ python main.py --data=mnist --model=pixel_rnn

Its output is as follows:

> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
> {'batch_size': 100,
>  'data': 'mnist',
>  'data_dir': 'data',
>  'display': False,
>  'grad_clip': 1,
>  'hidden_dims': 16,
>  'is_train': True,
>  'learning_rate': 0.001,
>  'log_level': 'INFO',
>  'max_epoch': 100000,
>  'model': 'pixel_rnn',
>  'out_hidden_dims': 32,
>  'out_recurrent_length': 2,
>  'random_seed': 123,
>  'recurrent_length': 7,
>  'sample_dir': 'samples',
>  'save_step': 1000,
>  'test_step': 100,
>  'use_dynamic_rnn': False,
>  'use_gpu': True,
>  'use_residual': False}
> [09-22 12:18:55] Skip creating directory: data/mnist
> [09-22 12:18:55] Skip creating directory: samples/mnist/checkpoints/data=mnist/batch_size=100/grad_clip=1/hidden_dims=16/learning_rate=0.001/model=pixel_rnn/out_hidden_dims=32/out_recurrent_length=2/recurrent_length=7/use_dynamic_rnn=False/use_gpu=True/use_residual=False/
> Traceback (most recent call last):
>   File "main.py", line 139, in <module>
>     tf.app.run()
>   File "/home/clu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv))
>   File "main.py", line 71, in main
>     mnist = input_data.read_data_sets(DATA_DIR, one_hot=True)
>   File "/home/clu/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 189, in read_data_sets
>     SOURCE_URL + TRAIN_IMAGES)
>   File "/home/clu/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 157, in maybe_download
>     urllib.request.urlretrieve(source_url, temp_file_name)
>   File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
>     return opener.retrieve(url, filename, reporthook, data)
>   File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
>     fp = self.open(url, data)
>   File "/usr/lib/python2.7/urllib.py", line 213, in open
>     return getattr(self, name)(url)
>   File "/usr/lib/python2.7/urllib.py", line 350, in open_http
>     h.endheaders(data)
>   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
>     self.send(msg)
>   File "/usr/lib/python2.7/httplib.py", line 859, in send
>     self.connect()
>   File "/usr/lib/python2.7/httplib.py", line 836, in connect
>     self.timeout, self.source_address)
>   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
>     raise err
> **IOError: [Errno socket error] [Errno 101] Network is unreachable**

Could you kindly give any suggestion about it? Thanks.

**Comment by aahusarenko** [comment]
I get the same IOError, but when training the mnist_saved_model. I have had proxy issues in the past, so I've been troubleshooting that, but so far have not been able to find a solution.

**Comment by ramakrishnapallala** [comment]
I am also facing the same issue, @aahusarenko were you able to find a solution?
